version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: almoxarifado_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: almoxarifado
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - almoxarifado_network

  app:
    build: .
    container_name: almoxarifado_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: almoxarifado
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    networks:
      - almoxarifado_network

volumes:
  mysql_data:

networks:
  almoxarifado_network:
    driver: bridge